---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/movies":
    get:
      summary: list movies
      tags:
      - Movies
      responses:
        '200':
          description: successful
    post:
      summary: Creates a movie
      tags:
      - Movies
      parameters: []
      responses:
        '201':
          description: movie created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: foo
                description:
                  type: string
                  example: bar
              required:
              - name
  "/movies/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show movie
      tags:
      - Movies
      responses:
        '200':
          description: successful
    patch:
      summary: update movie by id
      tags:
      - Movies
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      - name: name
        in: header
        description: name
        schema:
          type: string
      - name: description
        in: header
        description: description
        schema:
          type: string
      responses:
        '200':
          description: success
        '404':
          description: not_found
    delete:
      summary: delete movie
      tags:
      - Movies
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
